version: '3.9'

sevices:
  db:
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_DB=todo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
